// Namuna (demo) WizardData — CPSR_KR_dossier_v7_3 (kitob) dagi "Example Serum"
// ma'lumotlari bilan. scripts/sample-pdf.ts va tests/pdf-report.test.ts ikkalasi
// ham shu fixture'dan foydalanadi (bir xil ma'lumot = bir xil natija).

import type { WizardData } from "@/lib/wizard-types";

export const sampleProductWizard: WizardData = {
  productInfo: {
    productName: "Example Serum (데모 · DEMO)",
    productType: "씻어내지 않는 얼굴용 세럼 (Leave-on facial serum)",
    targetUser: "성인",
    rinseType: "leave-on",
    applicationArea: "얼굴",
    manufacturer: "Example Manufacturer (Example site)",
    responsibleSeller: "Example Cosmetics Co.",
    productCode: "",
    batchRef: "",
    salesMarket: "대한민국(KR)",
    version: "Rev. 1.3",
    refNo: "CPSR-2026-0001",
    responsiblePerson: "",
    gmpSite: "",
    useInstructions: "1일 1회 얼굴에 0.8 g을 도포한다 (씻어내지 않음, leave-on).",
    cmrDeclaration: "",
    nanoDeclaration: "",
    hasFragrance: "no",
    hasColorant: "no",
  },
  ingredients: [
    {
      id: "r1",
      tradeName: "정제수",
      percentInProduct: "90.80",
      components: [
        {
          id: "c1",
          inciName: "AQUA",
          cas: "7732-18-5",
          percentActiveInRaw: "100",
          functionRole: "용제",
          dermalAbsorptionPercent: "100",
          noael: "90000",
          cramerClass: "",
          tox: {
            acuteToxicity: "unknown",
            skinIrritation: "unknown",
            eyeIrritation: "unknown",
            skinSensitization: "unknown",
            genotoxicity: "unknown",
            carcinogenicity: "unknown",
            reproductiveToxicity: "unknown",
            phototoxicity: "unknown",
            notes: "",
          },
          molecularWeight: "18.02",
          physicalForm: "무색 액체",
          solubility: "용매",
          logKow: "-",
          uvAbsorption: "없음",
        },
      ],
    },
    {
      id: "r2",
      tradeName: "글리세린",
      percentInProduct: "5.00",
      components: [
        {
          id: "c2",
          inciName: "GLYCERIN",
          cas: "56-81-5",
          percentActiveInRaw: "100",
          functionRole: "보습제",
          dermalAbsorptionPercent: "100",
          noael: "2000",
          cramerClass: "",
          tox: {
            acuteToxicity: "unknown",
            skinIrritation: "available",
            eyeIrritation: "unknown",
            skinSensitization: "available",
            genotoxicity: "unknown",
            carcinogenicity: "unknown",
            reproductiveToxicity: "unknown",
            phototoxicity: "unknown",
            notes: "문헌",
          },
          molecularWeight: "92.09",
          physicalForm: "무색 점성액",
          solubility: "물 완전 혼화",
          logKow: "~-1.76",
          uvAbsorption: "없음",
        },
      ],
    },
    {
      id: "r3",
      tradeName: "나이아신아마이드",
      percentInProduct: "3.00",
      components: [
        {
          id: "c3",
          inciName: "NIACINAMIDE",
          cas: "98-92-0",
          percentActiveInRaw: "100",
          functionRole: "컨디셔닝/활성",
          dermalAbsorptionPercent: "100",
          noael: "1000",
          cramerClass: "",
          tox: {
            acuteToxicity: "unknown",
            skinIrritation: "available",
            eyeIrritation: "unknown",
            skinSensitization: "available",
            genotoxicity: "unknown",
            carcinogenicity: "unknown",
            reproductiveToxicity: "unknown",
            phototoxicity: "unknown",
            notes: "문헌",
          },
          molecularWeight: "122.12",
          physicalForm: "백색 결정",
          solubility: "물 가용 (~500 g/L)",
          logKow: "~-0.37",
          uvAbsorption: "낮음",
        },
      ],
    },
    {
      id: "r4",
      tradeName: "페녹시에탄올",
      percentInProduct: "0.90",
      components: [
        {
          id: "c4",
          inciName: "PHENOXYETHANOL",
          cas: "122-99-6",
          percentActiveInRaw: "100",
          functionRole: "보존제",
          dermalAbsorptionPercent: "100",
          noael: "500",
          cramerClass: "",
          tox: {
            acuteToxicity: "unknown",
            skinIrritation: "unknown",
            eyeIrritation: "unknown",
            skinSensitization: "unknown",
            genotoxicity: "unknown",
            carcinogenicity: "unknown",
            reproductiveToxicity: "unknown",
            phototoxicity: "unknown",
            notes: "",
          },
          molecularWeight: "138.16",
          physicalForm: "무색 액체",
          solubility: "물 부분 (~2.67%)",
          logKow: "~1.16",
          uvAbsorption: "없음",
        },
      ],
    },
    {
      id: "r5",
      tradeName: "레티놀",
      percentInProduct: "0.30",
      components: [
        {
          id: "c5",
          inciName: "RETINOL",
          cas: "68-26-8",
          percentActiveInRaw: "100",
          functionRole: "활성/컨디셔닝",
          dermalAbsorptionPercent: "100",
          noael: "5",
          cramerClass: "",
          tox: {
            acuteToxicity: "unknown",
            skinIrritation: "available",
            eyeIrritation: "unknown",
            skinSensitization: "available",
            genotoxicity: "unknown",
            carcinogenicity: "unknown",
            reproductiveToxicity: "unknown",
            phototoxicity: "unknown",
            notes: "EU 2024/996 at-limit 우려",
          },
          molecularWeight: "286.45",
          physicalForm: "담황 고체/오일",
          solubility: "물 난용 · 유상 가용",
          logKow: "~5.7",
          uvAbsorption: "있음 (~325 nm)",
        },
      ],
    },
  ],
  productQuality: {
    physicalForm: "맑은 점성 액체 · 옅은 노랑 · 특이취",
    ph: "5.8 (관리범위 5.5-6.1)",
    viscosityRange: "1,200 cP (1,000-1,400)",
    stabilityResult: "",
    paoMonths: "",
    microbialLimitResult: "",
    challengeTestResult: "",
    heavyMetalsResult: "",
    packagingMaterial: "에어리스 펌프 (재질 검토필요)",
    packagingSafetyNote: "",
    allergenNote: "해당 없음 — 향료 미배합",
    microCategory: "Cat2",
    specificBacteriaResult: "",
    impurityDioxaneResult: "",
    impurityNitrosamineResult: "정성: 2차 아민계 원료 없음 — 형성 리스크 낮음 (정량 검토필요)",
    packagingMigrationResult: "",
    stabilityAcceleratedResult: "40°C/75%RH 4주 — 상분리 없음 (PASS)",
    stabilityLongTermResult: "",
    stabilityFreezeThawResult: "",
    stabilityPhotoResult: "",
  },
  exposure: { amountG: "0.8", retentionFactor: "1.0", bodyWeightKg: "60", frequency: "1" },
  certification: {
    assessorName: "",
    assessorPosition: "",
    assessorQualification: "",
    reviewDate: "",
    draftNotes: "",
    selfCertified: false,
  },
};
